### ISSUE TITLE
BaseTimeEntity 생성 및 상속

### ISSUE THREAD

**Issue by WindowH22** [FinalProject-AIPARK/JenaPark-BE#31]
## 설명

BaseTimeEntity를 통해 date 관련 데이터를 다루기 편하게 한다.

## 할 일

- [ ] BaseTimeEntity 생성
- [ ] BaseTimeEntity 상속걸어주기

**Comment by yoongyum** [comment]
회원가입 했을 때 날짜가 자동으로 주입되지 않습니다.
코드 수정 바랍니다.

**Comment by WindowH22** [comment]
수정했습니다. 확인 부탁드립니다.
